const ENDPOINT="https://script.google.com/macros/s/AKfycbzTWfV1dCy6weL-J8t-nm8to7gtG83pFelbZkkzEEk0pgw_bs2-LyU_VVqZOQsfmKEJ/exec";
const choices=["لا أعاني منها","بسيطة","متوسطة","كبيرة","كبيرة جدًا"];
const domains=[
{title:"المشكلات النفسية والانفعالية",items:["أعاني من ضغوط نفسية بسبب متطلبات رعاية ابني/ابنتي.","أعاني من الإرهاق النفسي نتيجة المسؤوليات اليومية المرتبطة برعاية ابني/ابنتي.","أواجه صعوبة في التحكم في انفعالاتي عند التعامل مع المشكلات المرتبطة بابني/ابنتي.","أشعر بالحزن بسبب التحديات التي يواجهها ابني/ابنتي.","أشعر بالعجز في بعض المواقف المتعلقة برعاية ابني/ابنتي.","أواجه صعوبة في استعادة توازني النفسي بعد المواقف الصعبة.","أشعر بأن المسؤوليات المرتبطة بابني/ابنتي تفوق قدرتي أحيانًا.","أواجه صعوبة في تخصيص وقت لراحتي واحتياجاتي النفسية."]},
{title:"المشكلات السلوكية والتربوية",items:["أواجه صعوبة في التعامل مع التغيرات السلوكية المصاحبة لمرحلة المراهقة.","أواجه صعوبة في التعامل مع نوبات الغضب أو السلوكيات الصعبة لدى ابني/ابنتي.","أواجه صعوبة في تعليم ابني/ابنتي مهارات الاعتماد على النفس.","أواجه صعوبة في اختيار الأسلوب المناسب للتعامل مع بعض سلوكيات ابني/ابنتي.","أواجه صعوبة في التعامل مع التغيرات الجسدية والانفعالية المصاحبة للمراهقة.","أواجه صعوبة في توعية ابني/ابنتي بموضوعات البلوغ والخصوصية والحماية الشخصية.","أعاني من اختلاف أساليب أفراد الأسرة في التعامل مع ابني/ابنتي.","أواجه نقصًا في الإرشاد المتخصص الذي يساعدني على التعامل مع مشكلات ابني/ابنتي."]},
{title:"المشكلات التعليمية والتأهيلية",items:["أواجه صعوبة في الحصول على برنامج تعليمي يناسب قدرات ابني/ابنتي.","أعاني من عدم ملاءمة الخطة التعليمية المقدمة لاحتياجات ابني/ابنتي.","أواجه ضعفًا في التواصل بين الأسرة والمدرسة أو المركز.","أواجه صعوبة في الحصول على خدمات مساندة مناسبة، مثل التخاطب أو العلاج الوظيفي.","أعاني من نقص البرامج المناسبة للمراهقين ذوي اضطراب طيف التوحد.","أواجه صعوبة في تحديد قدرات ابني/ابنتي وميوله المهنية.","أعاني من محدودية فرص التدريب المهني المناسبة لابني/ابنتي.","أواجه نقصًا في المعلومات الواضحة عن الخيارات المتاحة بعد انتهاء المرحلة المدرسية."]},
{title:"المشكلات الأسرية والاجتماعية",items:["أعاني من ضعف تقبّل المجتمع لابني/ابنتي.","أعاني من عزلة ابني/ابنتي أو ضعف مشاركته الاجتماعية.","أواجه مشكلة تعرض ابني/ابنتي للتنمر أو الاستغلال، أو الخوف من حدوث ذلك.","أواجه صعوبة في اصطحاب ابني/ابنتي إلى المناسبات والأماكن العامة.","تتأثر علاقاتي الاجتماعية بسبب متطلبات رعاية ابني/ابنتي.","أعاني من نقص الدعم الذي أتلقاه من أفراد الأسرة.","أعاني من عدم فهم الآخرين لطبيعة اضطراب ابني/ابنتي واحتياجاته.","أواجه صعوبة في توفير أنشطة اجتماعية وترفيهية مناسبة لابني/ابنتي."]},
{title:"مشكلات الخدمات والدعم",items:["أواجه صعوبة في الوصول إلى المتخصصين المناسبين لحالة ابني/ابنتي.","أعاني من ارتفاع تكلفة الخدمات التعليمية أو التأهيلية.","أواجه نقصًا في المعلومات المتعلقة بحقوق ابني/ابنتي والخدمات المقدمة له.","أواجه صعوبة في التنسيق بين الجهات التي تقدم الخدمات لابني/ابنتي.","أعاني من عدم استمرارية الخدمات المقدمة بعد مرحلة الطفولة.","أواجه نقصًا في الإرشاد والمتابعة الموثوقة المقدمة للأسرة.","أواجه صعوبة في التحقق من صحة المعلومات المتعلقة باضطراب طيف التوحد.","أعاني من نقص المصادر الرقمية العربية الموثوقة التي تساعدني عند مواجهة مشكلة."]},
{title:"مشكلات الانتقال إلى الرشد والاستقلالية",items:["أواجه صعوبة في إعداد خطة لانتقال ابني/ابنتي من المدرسة إلى مرحلة الرشد.","أواجه صعوبة في تحديد الأولويات والاحتياجات المرتبطة بمرحلة رشد ابني/ابنتي.","أواجه صعوبة في تنمية قدرة ابني/ابنتي على الاعتماد على نفسه.","أعاني من عدم وضوح فرص التعليم أو التدريب المتاحة بعد المرحلة المدرسية.","أواجه صعوبة في اتخاذ القرارات المتعلقة بانتقال ابني/ابنتي إلى مرحلة الرشد.","أواجه صعوبة في إعداد ابني/ابنتي للعمل أو التدريب المهني.","أواجه نقصًا في الخطط والبرامج التي تنمي استقلالية ابني/ابنتي.","أواجه صعوبة في تحديد ترتيبات الرعاية المستقبلية المناسبة لابني/ابنتي عند تعذر قيامي بها."]}
];
const demographics=[["عمر الأم",["أقل من 30 سنة","من 30 إلى 39 سنة","من 40 إلى 49 سنة","50 سنة فأكثر"]],["المستوى التعليمي للأم",["أقل من الثانوية","الثانوية","الدبلوم","البكالوريوس","الدراسات العليا"]],["الحالة الاجتماعية",["متزوجة","مطلقة","أرملة","أخرى"]],["عمر الابن أو الابنة",["من 13 إلى 14 سنة","من 15 إلى 16 سنة","من 17 إلى 18 سنة"]],["جنس الابن أو الابنة",["ذكر","أنثى"]],["مستوى الدعم وفق التشخيص",["المستوى الأول: يحتاج إلى الدعم","المستوى الثاني: يحتاج إلى دعم كبير","المستوى الثالث: يحتاج إلى دعم كبير جدًا","غير محدد"]],["نوع البرنامج الحالي",["دمج مدرسي","فصل تربية خاصة","مركز رعاية أو تأهيل","تدريب مهني","لا يلتحق حاليًا ببرنامج","أخرى"]]];
const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
document.querySelector("#demographics").innerHTML=demographics.map(([q,opts],i)=>`<label class="field"><span>${esc(q)}</span><select name="d-${i}" required><option value="" disabled selected>اختاري الإجابة</option>${opts.map(o=>`<option>${esc(o)}</option>`).join("")}</select></label>`).join("");
document.querySelector("#domains").innerHTML=domains.map((d,di)=>`<section class="card domain"><div class="domainHead"><span>${String(di+1).padStart(2,"0")}</span><div><h2>${esc(d.title)}</h2><p>حددي درجة معاناتك خلال الأشهر الستة الماضية.</p></div></div>${d.items.map((item,ii)=>`<fieldset><legend>${ii+1}. ${esc(item)}</legend><div class="scale">${choices.map((c,ci)=>`<label><input type="radio" required name="q-${di}-${ii}" value="${ci+1}"><span>${esc(c)}</span></label>`).join("")}</div></fieldset>`).join("")}</section>`).join("");
document.querySelector("#domainChips").innerHTML=domains.map(d=>`<label><input type="checkbox" name="topDomains" value="${esc(d.title)}"><span>${esc(d.title)}</span></label>`).join("");
const form=document.querySelector("#survey"),progressText=document.querySelector("#progressText"),progressBar=document.querySelector("#progressBar"),error=document.querySelector("#error"),button=document.querySelector("#submitButton");
form.addEventListener("change",e=>{if(e.target.name?.startsWith("q-")){const n=document.querySelectorAll('input[name^="q-"]:checked').length;progressText.textContent=`تمت الإجابة عن ${n} من 48 عبارة`;progressBar.style.width=`${n/48*100}%`}});
form.addEventListener("submit",async e=>{e.preventDefault();error.hidden=true;const fd=new FormData(form),top=fd.getAll("topDomains");if(top.length!==3){error.textContent="فضلاً اختاري ثلاثة مجالات فقط.";error.hidden=false;document.querySelector("#domainChips").scrollIntoView({behavior:"smooth"});return}const ratings={};domains.forEach((d,di)=>d.items.forEach((_,ii)=>ratings[`${di}-${ii}`]=Number(fd.get(`q-${di}-${ii}`))));const payload={demographics:Object.fromEntries(demographics.map(([q],i)=>[q,fd.get(`d-${i}`)])),ratings,topDomains:top,topProblem:fd.get("topProblem"),supportNeed:fd.get("supportNeed"),aiUse:fd.get("aiUse"),aiReadiness:fd.get("aiReadiness"),otherProblem:fd.get("otherProblem")};button.disabled=true;button.textContent="جارٍ إرسال الإجابة...";try{await fetch(ENDPOINT,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});form.hidden=true;document.querySelector(".hero").hidden=true;document.querySelector("#thanks").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}catch{error.textContent="تعذر إرسال الإجابة. يرجى المحاولة مرة أخرى.";error.hidden=false;button.disabled=false;button.textContent="إرسال الإجابة"}});
